"use strict";
// functions/src/templates/bos.ts
Object.defineProperty(exports, "__esModule", { value: true });
exports.renderBoSHTML = renderBoSHTML;
function fmtCurrency(n) {
    return (n || 0).toLocaleString('en-US', { style: 'currency', currency: 'USD' });
}
function fmtDate(d) {
    if (!d)
        return 'N/A';
    const date = new Date(d);
    if (isNaN(date.getTime()))
        return 'N/A';
    return date.toLocaleDateString('en-US');
}
function renderBoSHTML(jacketData, seller, buyer) {
    const { vin, year, make, model, color, odometer, itemPrice, buyerFee, onlineFee, managementFee, miscFees = [], invoiceId, jacketNumber, auctionSaleDate } = jacketData;
    const total = (Number(itemPrice) || 0) + (Number(buyerFee) || 0) + (Number(onlineFee) || 0) + (Number(managementFee) || 0) + miscFees.reduce((s, f) => s + (Number(f.amount) || 0), 0);
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Dealer to Dealer Bill of Sale</title><style>@page{margin:24mm 16mm}html,body{font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,"Apple Color Emoji","Segoe UI Emoji";color:#111;margin:0;padding:0;font-size:12px}.container{max-width:800px;margin:0 auto}.header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #111;padding-bottom:8px;margin-bottom:12px}.brand h1{margin:0;font-size:20px}.brand .dba{font-size:12px;color:#333}.brand .contact{font-size:12px;color:#333;margin-top:4px}.title{font-size:20px;font-weight:800;margin:0;text-align:right}.row{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:12px}.card{border:1px solid #e5e5e5;border-radius:6px;padding:10px}.card h3{margin:0 0 6px;font-size:13px;letter-spacing:.2px}.grid{display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:8px;margin-top:10px}.cell{background:#f7f7f7;padding:8px;border:1px solid #e5e5e5;border-radius:4px}.section{margin-top:20px}.section h3{margin:0 0 8px;font-size:14px;border-bottom:1px solid #eee;padding-bottom:4px}.sign-row{display:flex;gap:16px;margin-top:25px}.sign{flex:1}.sign .label{margin-bottom:32px;border-bottom:1px solid #999;height:0}.sign .caption{font-size:11px;color:#333;margin-top:4px}.footer{text-align:center;font-size:10px;color:#444;margin-top:20px;line-height:1.4;border-top:1px solid #e5e5e5;padding-top:8px}</style></head>
<body><div class="container"><div class="header"><div class="brand"><h1>${seller.name}</h1>${seller.dba ? `<div class="dba">DBA ${seller.dba}</div>` : ""}<div class="contact">${seller.phone} | ${seller.email}</div></div><h2 class="title">Dealer to Dealer Bill of Sale</h2></div><div class="grid"><div class="cell"><strong>Invoice ID:</strong> ${invoiceId}</div><div class="cell"><strong>Jacket #:</strong> ${jacketNumber}</div><div class="cell"><strong>Date of Sale:</strong> ${fmtDate(auctionSaleDate)}</div><div class="cell"><strong>VIN:</strong> ${vin}</div></div><div class="row"><div class="card"><h3>SELLER</h3><div>${seller.name}</div><div>${seller.line1}</div><div>${seller.line2}</div></div><div class="card"><h3>BUYER ("SOLD TO")</h3><div><strong>${buyer.name}</strong></div><div>${buyer.line1}</div><div>${buyer.line2}</div><div>Phone: ${buyer.phone}</div><div>Email: ${buyer.email}</div></div></div><div class="section"><h3>VEHICLE INFORMATION</h3><div class="grid" style="grid-template-columns:2fr 1fr 1fr"><div class="cell"><strong>Vehicle</strong><br>${year} ${make} ${model}</div><div class="cell"><strong>Color</strong><br>${color}</div><div class="cell"><strong>Odometer</strong><br>${(odometer || 0).toLocaleString()}</div></div></div><div class="section"><h3>CONSIDERATION</h3><p>For the sum of <strong>${fmtCurrency(total)}</strong>, receipt of which is hereby acknowledged, the seller transfers possession free from all liens to the Buyer.</p></div><div class="sign-row"><div class="sign"><div class="label"></div><div class="caption">Authorized Seller Signature (Signature on File)</div></div><div class="sign"><div class="label"></div><div class="caption">Authorized Buyer Signature (Signature on File)</div></div></div><div class="footer">ALL SALES FINAL. ALL UNITS ARE SOLD AS-IS, WHERE-IS. NO RETURNS/EXCHANGES.<br>The undersigned seller affirms that they are the legal owner of the vehicle and have full authority to sell it. The vehicle is sold free and clear of all liens and encumbrances.</div></div></body></html>`;
    return html;
}
//# sourceMappingURL=bos.js.map